OPD_DATA_BASE/OPD_DATA_BASE/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from OPD_DATA_BASE import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('database.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

OPD_DATA_BASE/database/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='main'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AccountLoginView.as_view(), name='login'),
    path('logout/', views.AccountLogoutView.as_view(), name='logout'),
    path('library/', views.LibraryView.as_view(), name='library'),
    path('library/create/', views.CreateArticleView.as_view(),
         name='create_article'),
    path('library/<slug:slug>/delete/', views.DeleteArticleView.as_view(),
         name='delete_article'),
    path('library/<slug:slug>/update/', views.UpdateArticleView.as_view(),
         name='update_article'),
    path('library/<slug:slug>/', views.ArticleView.as_view(), name='article'),
    path('profile/<pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<pk>/update/', views.UpdateAccountView.as_view(),
         name='update_account'),
    path('library/<slug:slug>/download/', views.DownloadView.as_view(),
         name='download')
    ]

OPD_DATA_BASE/database/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models
from pytils.translit import slugify
from uuid import uuid4
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator


def article_directory_path(instance, filename):
    return "user_{0}/articles/{1}".format(instance.author.id, filename)


def validate_pdf_file(file):
    if file.name.split('.')[-1].lower() != "pdf":
        raise ValidationError("Разрешены только PDF файлы.")
    return file


class Account(AbstractUser):
    READER = 1
    AUTHOR = 2
    ROOT = 3

    ROLE_CHOICES = (
        (READER, 'Reader'),
        (AUTHOR, 'Author'),
        (ROOT, 'Root'),
    )

    username_validator = UnicodeUsernameValidator()

    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES,
                                            default=1)
    email = models.EmailField('Электронная почта', unique=True)
    username = models.CharField('Имя пользователя', unique=True,
                                max_length=150,
                                validators=[username_validator],
                                error_messages={
                                    "unique": _(
                                        "A user with that username already \
exists."),
                                }, )
    first_name = models.CharField('Имя', max_length=150)
    last_name = models.CharField('Фамилия', max_length=150)
    third_name = models.CharField('Отчество', max_length=150, blank=True,
                                  null=True)
    fullname = models.CharField(max_length=452)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.fullname

    def save(self, *args, **kwargs):
        self.fullname = f"{self.last_name} {self.first_name} \
{self.third_name}" if self.third_name else f"{self.last_name} \
{self.first_name}"
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'


class Keyword(models.Model):
    word = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.word

    class Meta:
        verbose_name = 'Ключевое слово'
        verbose_name_plural = 'Ключевые слова'


class Article(models.Model):
    title = models.CharField('Название статьи', max_length=128)
    abstract = models.TextField('Аннотация к статье')
    date_created = models.DateTimeField('Дата создания', auto_now_add=True)
    views = models.PositiveIntegerField('Количество просмотров', default=0)
    downloads = models.PositiveIntegerField('Количество загрузок', default=0)
    author = models.ForeignKey(Account, on_delete=models.DO_NOTHING,
                               related_name='articles', verbose_name='Автор')
    article = models.FileField('Статья', upload_to=article_directory_path,
                               validators=[validate_pdf_file])
    keywords = models.ManyToManyField(Keyword, related_name='articles')
    keywords_temp = models.CharField('Ключевые слова', max_length=255)
    slug = models.SlugField(max_length=255, verbose_name="URL", editable=False,
                            unique=True)
    is_active = models.BooleanField('Одобрено', default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(
                f'{self.title}-b\
y-{self.author.fullname}--{uuid4().hex[:4]}')
            while Article.objects.filter(slug=self.slug).exists():
                self.slug = slugify(
                    f'{self.title}-b\
y-{self.author.fullname}--{uuid4().hex[:4]}')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

OPD_DATA_BASE/database/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, ListView, DeleteView, \
    UpdateView, DetailView, View
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse, Http404
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.db.models import Q, F, Subquery, OuterRef, Count
from datetime import datetime
from .models import *


# Create your views here.


def index(request):
    return render(request, 'main/index.html')


class RegisterView(CreateView):
    model = Account
    fields = ['email', 'username', 'first_name', 'last_name', 'third_name',
              'password']
    template_name = 'main/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        form.instance.set_password(
            form.cleaned_data['password'])
        return super().form_valid(form)


class AccountLoginView(LoginView):
    template_name = 'main/login.html'


class AccountLogoutView(LoginRequiredMixin, LogoutView):
    pass


class LibraryView(ListView):
    template_name = 'main/elibrary.html'
    paginate_by = 30

    def get_queryset(self):
        query = self.request.GET.get('query')
        keywords = self.request.GET.get('keywords')
        keywords_block = self.request.GET.get('keywords_block')
        all_terms = self.request.GET.get('all_terms')
        queryset = Article.objects.filter(is_active=True,
                                          author__is_active=True).order_by(
            '-date_created')
        if query:
            search_terms = [term.strip() for term in query.split(',')]
            q_objects = Q()
            for term in search_terms:
                q_objects_temp = Q()
                date_term = None
                for fmt in (
                        "%d.%m.%Y", "%d.%m.%y", "%m.%d.%Y", "%m.%d.%y"):
                    try:
                        date_term = datetime.strptime(term, fmt).date()
                        q_objects_temp |= Q(date_created__date=date_term)
                        break
                    except ValueError:
                        pass
                if not date_term:
                    try:
                        day = int(term)
                        q_objects_temp |= Q(date_created__day=day)
                    except ValueError:
                        pass
                    try:
                        month = int(term)
                        q_objects_temp |= Q(date_created__month=month)
                    except ValueError:
                        pass
                    try:
                        year = int(term)
                        q_objects_temp |= Q(date_created__year=year)
                    except ValueError:
                        pass
                    q_objects_temp |= (
                            Q(title__iregex=term) |
                            Q(abstract__iregex=term) |
                            Q(author__fullname__iregex=term) |
                            Q(keywords__word__iregex=term)
                    )
                if all_terms:
                    q_objects &= q_objects_temp
                else:
                    q_objects |= q_objects_temp
            queryset = queryset.filter(q_objects).distinct()
        if keywords_block:
            keywords = [word.upper().strip() for word in keywords.split(',')]
            article_keywords = Article.objects.filter(
                pk=OuterRef('pk'),
                keywords__word__in=keywords).values(
                'pk').annotate(num_keywords=Count('keywords')).values(
                'num_keywords')
            queryset = queryset.annotate(
                num_keywords=Subquery(article_keywords)
            ).filter(num_keywords=len(keywords))
        return queryset


class DeleteArticleView(LoginRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('library')
    template_name = 'main/delete_article.html'

    def form_valid(self, form):
        if (self.object.author.id == self.request.user.id or
                self.request.user.role == 3):
            return super().form_valid(form)
        raise PermissionDenied("У вас нет прав для удаления данной статьи.")


class CreateArticleView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ['title', 'abstract', 'article', 'keywords_temp']
    template_name = 'main/create_article.html'
    success_url = reverse_lazy('library')

    def form_valid(self, form):
        if self.request.user.role >= 2:
            form.instance.author = self.request.user
            response = super().form_valid(form)
            keywords = form.cleaned_data.get('keywords_temp', '').split(',')
            for word in keywords:
                word = word.upper().strip()
                if word:
                    keyword, created = Keyword.objects.get_or_create(word=word)
                    self.object.keywords.add(keyword)
            return response
        raise PermissionDenied("У вас нет прав для загрузки статьи.")


class UpdateArticleView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = []
    template_name = 'main/update_article.html'
    success_url = reverse_lazy('library')

    def form_valid(self, form):
        if (form.instance.author.id == self.request.user.id or
                self.request.user.role == 3):
            form.instance.is_active = False
            return super().form_valid(form)
        raise PermissionDenied(
            "У вас нет прав для редактирования данной статьи.")


class ArticleView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = 'main/article.html'

    def get_object(self, queryset=None):
        queryset = self.get_queryset()
        article = super().get_object(queryset=queryset)
        if not article.is_active or not article.author.is_active:
            raise Http404("Статья не найдена или ещё не проверена модерацией.")
        return article

    def get(self, request, *args, **kwargs):
        article = self.get_object()
        if request.user != article.author:
            article.views = F('views') + 1
            article.save()
        return super().get(request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, DetailView):
    model = Account
    template_name = 'main/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        articles = context['object'].articles.all()
        articles = articles.filter(is_active=True) | articles.filter(
            author=user)
        context['articles'] = articles
        return context

    def get(self, request, *args, **kwargs):
        author = self.get_object()
        if not author.is_active:
            return redirect('library')
        return super().get(request, *args, **kwargs)


class UpdateAccountView(LoginRequiredMixin, UpdateView):
    model = Account
    fields = ['first_name', 'last_name', 'third_name']
    template_name = 'main/update_account.html'

    def get_success_url(self):
        return reverse_lazy('profile', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        if (form.instance.id == self.request.user.id or
                self.request.user.role == 3):
            return super().form_valid(form)
        raise PermissionDenied(
            "У вас нет прав для редактирования этого профиля.")


class DownloadView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, slug=kwargs['slug'])
        file = article.article
        if request.user != article.author:
            article.downloads = F('downloads') + 1
            article.save()
        response = FileResponse(file.open(), as_attachment=True,
                                filename=file.name)
        return response

OPD_DATA_BASE/database/templates/main/article.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}
Статья
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
{% endblock %}

{% block content %}

<style>
    .article_name {
        margin: 30px 0 30px 15px;
    }

    .content {
        margin-left: 15px;
    }

    .article-btn {
        margin: 30px 0 0 5px;
    }

    .download-btn {
        margin-left: 15px;
    }
</style>

{% if object.is_active and object.author.is_active %}
<h1 class="article_name">{{ object.title }}</h1>
<p class="content">Аннотация: {{ object.abstract }}</p>
<p class="content">Ключевые слова:</p>
<ul class="content">
    {% for keyword in object.keywords.all %}
        <li>
            <a href="{% url 'library' %}?query={{ keyword.word }}">{{ keyword.word }}</a>
        </li>
    {% endfor %}
</ul>
<a href="/profile/{{ object.author.id }}">
    <p class="content">Автор: {{ object.author.fullname }}</p></a>
<p class="content">Количество просмотров: {{ object.views }}</p>
<p class="content">Количество загрузок: {{ object.downloads }}</p>
<p class="content">Дата публикации: {{ object.date_created|date }}</p>
{% if user.is_authenticated %}
<a href="/library/{{ object.slug }}/download">
    <button type="button" class="btn btn-primary article-btn download-btn">Скачать</button></a>
{% if user.id == article.author.id or user.role == 3 %}
                                <a href="/library/{{ article.slug }}/update">
                                <button type="button"
                                        class="btn btn-primary article-btn">
                                    Редактировать
                                </button></a>
                                <a href="/library/{{ article.slug }}/delete">
                                <button type="button"
                                        class="btn btn-primary article-btn">
                                    Удалить
                                </button></a>
                                {% endif %}

{% endif %}
{% else %}
<h1>Статья ещё не прошла модерацию или её владелец был заблокирован/удалил свой аккаунт</h1>
{% endif %}
{% endblock %}

OPD_DATA_BASE/database/templates/main/base.html
<!doctype html>
{% load static %}
<html lang="ru" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title> {% block title %} {% endblock %} </title>

    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">

    {% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    {% endblock %}

    <style> {% block style %} {% endblock %} </style>
</head>
<body>

<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom head">
    <div class="col-md-3 mb-2 mb-md-0">
        <a href="/"
           class="d-inline-flex link-body-emphasis text-decoration-none">
                <img src="{% static 'media/logo.png' %}" width="60" height="60"/>
            </svg>
        </a>
    </div>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 head-button">
        <li><a href="/"
               class="nav-link px-2 {% if request.path == '/' %}link-secondary{% endif %}">Главная</a></li>
        <li><a href="/library"
               class="nav-link px-2 {% if request.path == '/library/' %}link-secondary{% endif %}">Электронная библиотека</a></li>
        {% if user.is_authenticated and user.role == 2 or user.role == 3 %}
        <li><a href="/library/create"
               class="nav-link px-2 {% if request.path == '/library/create/' %}link-secondary{% endif %}">Добавить статью</a></li>
        {% endif %}
    </ul>

    <div class="col-md-12 col-xl-3 text-end head-button">
        {% if user.is_authenticated %}
        <form action="/logout/" method="post" class="logout_form">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Выход из аккаунта" id="exit-btn">
        </form>

        <a href="/profile/{{ request.user.id }}">
            <button type="button" class="btn btn-primary">Профиль</button></a>
        {% else %}
        <a href="/login">
            <button type="button" class="btn btn-outline-primary me-2">Вход
            </button></a>
        <a href="/register">
            <button type="button" class="btn btn-primary">Регистрация</button>
        </a>
        {% endif %}
    </div>
</header>

<main class="body">
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</main>

</body>
</html>

OPD_DATA_BASE/database/templates/main/create_article.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}
Добавление статьи
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/create_article.css' %}" type="text/css">
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="form-article">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'media/logo.png' %}" alt=""
         width="60" height="60">
    {% if user.is_authenticated and user.role == 2 or user.role == 3 %}
    <h1 class="h3 mb-3 fw-normal">Добавление статьи</h1>
    {{ form.as_p }}
    <div class="keytext">Ключевые слова записываются через запятую. Пример: ключевое слово 1, ключевое слово 2, ключевое слово 3</div>
    <button class="btn btn-primary w-100 py-2" type="submit" value="Save">
        Добавить статью
    </button>
    {% else %}
    <h1>Статьи могут добавлять только авторизированные пользователи, которые являются авторами!</h1>
    {% endif %}
</form>
{% endblock %}

OPD_DATA_BASE/database/templates/main/delete_article.html
{% extends 'main/base.html' %}

{% load static %}



{% block title %}
Удаление статьи
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
{% endblock %}

{% block content %}
{% if user.id == object.author.id or user.role == 3 %}

<style>
    .delete-page {
        text-align: center;
        margin-top: 30px;
    }
    .delete-button {
        margin-left: 15px;
    }
</style>

<form method="post">{% csrf_token %}
    <p class="delete-page">Вы действительно хотите удалить статью "{{ object }}"?</p>
    {{ form }}
    <div class="delete-page">
        <input type="submit" value="Подтвердить">
    <a href="/library" class="delete-button">
        <input type="button" value="Отмена">
    </a>
    </div>
</form>
{% else %}
<h1>Статью может удалять только её авторизированный владелец или админ!</h1>
{% endif %}
{% endblock %}

OPD_DATA_BASE/database/templates/main/elibrary.html
{% extends 'main/base.html' %}

{% load static %}


{% block title %}
Библиотека
{% endblock %}


{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elibrary.css' %}" type="text/css"
{% endblock %}

{% block content %}

<h1 class="page-title">Библиотека</h1>

<p class="page-title">
    Искать статьи можно по названию, аннотации, ключевым словам, дате загрузки и автору.
    Если вы планируете искать сразу по нескольким параметрам или по нескольким ключевым словам, то используйте запятые для разделения.
</p>

<form method="GET" action="{% url 'library' %}" class="page-title search-form">
    <input type="text" name="query" placeholder="Поиск..." value="{{ request.GET.query }}" class="search-line">
    <div id="keywords_input" style="display: {% if request.GET.keywords_block %}block{% else %}none{% endif %};">
        <input type="text" name="keywords" placeholder="Ключевые слова через запятую" value="{{ request.GET.keywords }}">
    </div>
    <label>
        <input type="checkbox" id="keywords_checkbox" name="keywords_block" {% if request.GET.keywords_block %}checked{% endif %}>
        Обязательные ключевые слова
    </label>
    <label>
        <input type="checkbox" name="all_terms" {% if request.GET.all_terms %}checked{% endif %}>
        Более точный запрос
    </label>
    <button type="submit">Поиск</button>
</form>

<script>
    document.getElementById('keywords_checkbox').addEventListener('change', function() {
        var keywordsInput = document.getElementById('keywords_input');
        if (this.checked) {
            keywordsInput.style.display = 'block';
        } else {
            keywordsInput.style.display = 'none';
        }
    });
</script>

<div class="album py-5">
    <div class="container elibrary_container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for article in article_list %}
            {% if article.author.is_active %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ article.title }}</p>
                        <div>
                            <div class="d-block mb-2">
                                <div class="date_and_download menu-table">
                                   <a href="/library/{{ article.slug }}">
                                        <button type="button"
                                                class="btn btn-sm btn-primary">
                                            <span>Скачать</span>
                                        </button></a>
                                    <p class="content">Дата публикации: {{ article.date_created|date }}</p>
                                </div>
                                {% if user.id == article.author.id or user.role == 3 %}
                                <a href="/library/{{ article.slug }}/update">
                                <button type="button"
                                        class="btn btn-sm btn-outline-secondary">
                                    Редактировать
                                </button></a>
                                <a href="/library/{{ article.slug }}/delete">
                                <button type="button"
                                        class="btn btn-sm btn-outline-secondary delete_btn">
                                    Удалить
                                </button></a>
                                {% endif %}
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-2 menu-table">
                                <a href="/profile/{{ article.author.id }}">
                                <small class="text-body-secondary">
                                    {{ article.author.fullname }}</small></a>
                                <small class="text-body-secondary" title="Количество скачиваний">
                                    Cкачиваний: {{ article.downloads }}</small>
                                <small class="text-body-secondary" title="Количество просмотров">
                                    Просмотров: {{ article.views }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% empty %}
            <h1>Пока здесь пусто...</h1>
            {% endfor %}

        </div>
    </div>
</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}

OPD_DATA_BASE/database/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}
Главная
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
{% endblock %}

{% block content %}
    <h1 class="header">Добро пожаловать на сайт электронной библиотеки!</h1>
{% endblock %}

OPD_DATA_BASE/database/templates/main/login.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}
Вход
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="form-login">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'media/logo.png' %}" alt=""
         width="60" height="60">
    <h1 class="h3 mb-3 fw-normal">Вход</h1>
    {{ form.as_p }}
    <button class="btn btn-primary w-100 py-2" type="submit" value="Save">
        Вход
    </button>
</form>
{% endblock %}

OPD_DATA_BASE/database/templates/main/profile.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}
Профиль
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css">
{% endblock %}

{% block content %}
{% if object.is_active %}
<h1 class="info">{{ object.fullname }}</h1>
<p class="info">Почта: {{ object.email }}</p>
<p class="info">Права:
{% if object.role == 1 %}
    Читатель
  {% elif object.role == 2 %}
    Автор
  {% elif object.role == 3 %}
    Админ
  {% endif %}
</p>
<p class="info">Дата регистрации: {{ object.date_joined|date }}</p>
{% if object.id == user.id or user.role == 3 %}
<a href="/profile/{{ object.id }}/update">
    <button type="button" class="btn btn-primary button-redacc">Редактировать аккаунт</button></a>
{% endif %}

<div class="album py-5 profile-article">
    <div class="container container-profile">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for article in articles %}
            {% if article.is_active or article.author.id == user.id %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ article.title }}</p>
                        <div>
                            <div class="d-block mb-2">
                                <div class="date_and_download menu-table">
                                   <a href="/library/{{ article.slug }}">
                                        <button type="button"
                                                class="btn btn-sm btn-primary">
                                            <span>Скачать</span>
                                        </button></a>
                                    <p class="content">Дата публикации: {{ article.date_created|date }}</p>
                                </div>
                                {% if user.id == article.author.id or user.role == 3 %}
                                <a href="/library/{{ article.slug }}/update">
                                <button type="button"
                                        class="btn btn-sm btn-outline-secondary">
                                    Редактировать
                                </button></a>
                                <a href="/library/{{ article.slug }}/delete">
                                <button type="button"
                                        class="btn btn-sm btn-outline-secondary">
                                    Удалить
                                </button></a>
                                {% endif %}
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-2 menu-table">
                                <a href="/profile/{{ article.author.id }}">
                                <small class="text-body-secondary">
                                    {{ article.author.fullname }}</small></a>
                                <small class="text-body-secondary" title="Количество скачиваний">
                                    Cкачиваний: {{ article.downloads }}</small>
                                <small class="text-body-secondary" title="Количество просмотров">
                                    Просмотров: {{ article.views }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            {% empty %}
            <h1>Пока здесь пусто...</h1>
            {% endfor %}
        </div>
    </div>
</div>

{% else %}
<h1>Аккаунт удалён или заблокирован</h1>
{% endif %}
{% endblock %}

OPD_DATA_BASE/database/templates/main/update_account.html
{% extends 'main/base.html' %}

{% load static %}

{% block title %}
Редактирование аккаунта
{% endblock %}

{% block additional_head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'media/logo.png' %}" alt=""
         width="60" height="60">
    {% if user.id == object.id or user.role == 3 %}
    <h1 class="h3 mb-3 fw-normal">Редактирование аккаунта</h1>
    {{ form.as_p }}
    <button class="btn btn-primary w-100 py-2" type="submit" value="Save">
        Редактировать аккаунт
    </button>
    {% else %}
    <h1>Аккаунт может редактировать только его авторизированный владелец или админ!</h1>
    {% endif %}
</form>
{% endblock %}